env:
  global:
    - secure: UDORPffOmJ4Ht0P9jGM8w2MhDpSBivIet4iJEW5q9Hx5tzTt7FUg2o9Tjl1EjGfM4khCBjjYQ9tmtOruY62wJoy4O91vo83iPhb58weaL81uvbd4WMUahcAwjB1U/qmS2UUmje5SO3pNswV49ZKK8aVy5QgGXLYbl+vc5ll89To=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly llvm
  - git clone https://github.com/carlhuda/cargo
  - cd cargo
  - git submodule init
  - git submodule update
  - make
  - cd ..
  - sudo mv cargo/target/cargo* /usr/local/bin
  - sudo mv cargo/target/lib* /usr/local/lib
  - rm -rf cargo
script:
  - make build doc
notifications:
  email:
    - tophattedcoder@gmail.com
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh